export const ROUTE_SCHEDULES_UPDATED = 'Junio 2026';

export const DAY_LABELS = {
  LUN: 'Lunes',
  MAR: 'Martes',
  MIE: 'Miércoles',
  JUE: 'Jueves',
  VIE: 'Viernes',
  SAB: 'Sábado',
};

export const ROUTE_SCHEDULES = [
  {
    macroRoute: 'SUR ORIENTE',
    macroCode: '102815001',
    microCode: 'SR0101',
    neighborhoods: ['Ciudad Jardín', 'Pinos de Oriente', 'La Cabaña'],
    frequency: ['LUN'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'SUR ORIENTE',
    macroCode: '102815001',
    microCode: 'SR0102',
    neighborhoods: ['Xativilla', 'Fuente Higueras', 'Lanceros', 'Conjunto Fénix'],
    frequency: ['LUN'],
    schedule: '9:00 am a 2:00 pm',
  },
  {
    macroRoute: 'SUR ORIENTE',
    macroCode: '102815001',
    microCode: 'SR0103',
    neighborhoods: ['Cooservicios', 'Ciudadela Sol de Oriente', 'Villa Bachué'],
    frequency: ['LUN'],
    schedule: '11:00 am a 2:00 pm',
  },
  {
    macroRoute: 'SUR ORIENTE',
    macroCode: '102815001',
    microCode: 'SR0104',
    neighborhoods: ['Altos de Cooservicios', 'Cooservicios', 'Multifamiliar Cooservicios'],
    frequency: ['LUN'],
    schedule: '8:00 am a 11:00 am',
  },
  {
    macroRoute: 'SUR ORIENTE',
    macroCode: '102815001',
    microCode: 'SR0105',
    neighborhoods: ['Prados de Alcalá', 'Portal del Bolívar', 'Minuto de Dios', 'Portal de la UNAD', 'Praderas del Hunza', 'Portal Sol de Oriente', 'Multifamiliar Bosques de la Ponderosa'],
    frequency: ['LUN'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'SUR ORIENTE',
    macroCode: '102815001',
    microCode: 'SR0106',
    neighborhoods: ['Sagrado Corazón', 'La Florida'],
    frequency: ['MIE'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'SUR ORIENTE',
    macroCode: '102815001',
    microCode: 'SR0107',
    neighborhoods: ['La Perla', 'La Granja Sur', 'San Francisco', 'Conjunto Manta Real'],
    frequency: ['MIE'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'SUR ORIENTE',
    macroCode: '102815001',
    microCode: 'SR0108',
    neighborhoods: ['Santiago de Tunja', 'Tunjuelito', 'Nazareth', 'Doña Eva Etapa I', 'Bochica'],
    frequency: ['VIE'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'SUR ORIENTE',
    macroCode: '102815001',
    microCode: 'SR0109',
    neighborhoods: ['Urbanización Sol de Oriente', 'Portal de Otoño', 'San Antonio'],
    frequency: ['VIE'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'SUR OCCIDENTE',
    macroCode: '102915001',
    microCode: 'SC0201',
    neighborhoods: ['Bolívar'],
    frequency: ['LUN'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'SUR OCCIDENTE',
    macroCode: '102915001',
    microCode: 'SC0202',
    neighborhoods: ['La Siberia', 'Surinama'],
    frequency: ['LUN'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'SUR OCCIDENTE',
    macroCode: '102915001',
    microCode: 'SC0203',
    neighborhoods: ['San Carlos', 'Plaza de Mercado'],
    frequency: ['MAR', 'VIE'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'SUR OCCIDENTE',
    macroCode: '102915001',
    microCode: 'SC0204',
    neighborhoods: ['El Carmen', 'Bello Horizonte'],
    frequency: ['MAR'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'SUR OCCIDENTE',
    macroCode: '102915001',
    microCode: 'SC0205',
    neighborhoods: ['La Fuente etapa I y etapa II', 'Conjunto La Esperanza'],
    frequency: ['MIE'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'SUR OCCIDENTE',
    macroCode: '102915001',
    microCode: 'SC0206',
    neighborhoods: ['La Fuente etapa III', 'etapa IV y etapa V'],
    frequency: ['MIE'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'SUR OCCIDENTE',
    macroCode: '102915001',
    microCode: 'SC0207',
    neighborhoods: ['La María', 'Sanitas'],
    frequency: ['MIE'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'SUR OCCIDENTE',
    macroCode: '102915001',
    microCode: 'SC0208',
    neighborhoods: ['El Cortijo', 'Mirador Escandinavo', 'Colinas de San Fernando'],
    frequency: ['JUE'],
    schedule: '11:00 am a 2:00 pm',
  },
  {
    macroRoute: 'SUR OCCIDENTE',
    macroCode: '102915001',
    microCode: 'SC0209',
    neighborhoods: ['Los Andes', 'Paraíso'],
    frequency: ['JUE'],
    schedule: '8:30 am a 11:00 pm',
  },
  {
    macroRoute: 'SUR OCCIDENTE',
    macroCode: '102915001',
    microCode: 'SC0210',
    neighborhoods: ['La Calleja', 'Los Trigales', 'San Diego'],
    frequency: ['VIE'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'SUR OCCIDENTE',
    macroCode: '102915001',
    microCode: 'SC0211',
    neighborhoods: ['Conjunto residencial Doña Limbania'],
    frequency: ['JUE'],
    schedule: '3:00 pm a 6:00 pm',
  },
  {
    macroRoute: 'SUR OCCIDENTE',
    macroCode: '102915001',
    microCode: 'SC0212',
    neighborhoods: ['Tras del Alto', 'Altamira parte baja', 'Mirador de la Fuente'],
    frequency: ['MIE'],
    schedule: '4:00 pm a 6:30 pm',
  },
  {
    macroRoute: 'CENTRO',
    macroCode: '103015001',
    microCode: 'CE0301',
    neighborhoods: ['Conjunto El Bosque', 'Santa Bárbara parte baja', 'Las Banderas', 'Urbanización El Bosque', 'El Bosque'],
    frequency: ['LUN'],
    schedule: '8:30 am a 2:30 pm',
  },
  {
    macroRoute: 'CENTRO',
    macroCode: '103015001',
    microCode: 'CE0302',
    neighborhoods: ['Urbanización Central', 'San Laureano'],
    frequency: ['LUN'],
    schedule: '8:30 am a 2:30 pm',
  },
  {
    macroRoute: 'CENTRO',
    macroCode: '103015001',
    microCode: 'CE0303',
    neighborhoods: ['Maldonado', 'Conjunto Juan Ángel', 'San Juan'],
    frequency: ['MAR'],
    schedule: '8:30 am a 2:30 pm',
  },
  {
    macroRoute: 'CENTRO',
    macroCode: '103015001',
    microCode: 'CE0304',
    neighborhoods: ['Belalcázar', 'Jorge Eliécer Gaitán', 'Conjunto Mirador Universitario', 'Conjunto Residencial Monte Azul'],
    frequency: ['MAR'],
    schedule: '8:30 am a 2:30 pm',
  },
  {
    macroRoute: 'CENTRO',
    macroCode: '103015001',
    microCode: 'CE0305',
    neighborhoods: ['Sector los Hongos', 'Centro', 'Avenida Maldonado', 'La Sexta', 'Avenida Universitaria'],
    frequency: ['LUN', 'MIE'],
    schedule: '4:30 pm a 6:30 pm',
  },
  {
    macroRoute: 'CENTRO',
    macroCode: '103015001',
    microCode: 'CE0306',
    neighborhoods: ['Las Nieves', 'Conjunto Boulevar Las Nieves y Conjunto Céntrico', 'Pirandelo'],
    frequency: ['JUE'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'CENTRO',
    macroCode: '103015001',
    microCode: 'CE0307',
    neighborhoods: ['Consuelo', 'Hunza', 'Castillos de Oriente'],
    frequency: ['MIE'],
    schedule: '8:30 am a 2:30 pm',
  },
  {
    macroRoute: 'CENTRO',
    macroCode: '103015001',
    microCode: 'CE0308',
    neighborhoods: ['El Rodeo', 'Lidueña', 'Universidad Antonio Nariño', 'Conjunto Residencial LuzMa'],
    frequency: ['JUE'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'CENTRO',
    macroCode: '103015001',
    microCode: 'CE0309',
    neighborhoods: ['San Ignacio', 'Conjunto Los Laureles', 'Edificio Rosario Plaza'],
    frequency: ['JUE'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'CENTRO',
    macroCode: '103015001',
    microCode: 'CE0310',
    neighborhoods: ['Popular', 'Parque Santander'],
    frequency: ['MAR'],
    schedule: '11:30 am a 2:30 pm',
  },
  {
    macroRoute: 'CENTRO',
    macroCode: '103015001',
    microCode: 'CE0311',
    neighborhoods: ['Centenario', 'Condominio El Topo', 'Nueva Santa Bárbara', 'Santa Bárbara parte Alta', 'Conjunto Residencial Reina Sofía I'],
    frequency: ['JUE'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'CENTRO',
    macroCode: '103015001',
    microCode: 'CE0312',
    neighborhoods: ['Santa Lucía', 'Conjunto Monte Pino', 'Torre Zoaty'],
    frequency: ['MAR'],
    schedule: '8:30 am a 2:30 pm',
  },
  {
    macroRoute: 'CENTRO',
    macroCode: '103015001',
    microCode: 'CE0313',
    neighborhoods: ['Suárez'],
    frequency: ['VIE'],
    schedule: '10:30 am a 2:00 pm',
  },
  {
    macroRoute: 'CENTRO',
    macroCode: '103015001',
    microCode: 'CE0314',
    neighborhoods: ['Aquimín', 'Edificio Multifamiliar El Bosque'],
    frequency: ['VIE'],
    schedule: '8:00 am a 10:30 pm',
  },
  {
    macroRoute: 'CENTRO',
    macroCode: '103015001',
    microCode: 'CE0315',
    neighborhoods: ['Centro', 'sector comercio', 'Funeraria San Francisco'],
    frequency: ['LUN', 'MAR', 'MIE', 'JUE', 'VIE'],
    schedule: '2:00 pm a 5:00 pm',
  },
  {
    macroRoute: 'NOR ORIENTE',
    macroCode: '103115001',
    microCode: 'NR0401',
    neighborhoods: ['Mesopotamia', 'Conjunto Residencial La Catleya', 'Edificio Luz Alejandra', 'Conjunto Residencial del Norte', 'Conjunto Residencial Acrópolis II', 'La Pradera', 'Edificio Mediterráneo'],
    frequency: ['SAB'],
    schedule: '7:30 am a 2:00 pm',
  },
  {
    macroRoute: 'NOR ORIENTE',
    macroCode: '103115001',
    microCode: 'NR0402',
    neighborhoods: ['La Glorieta', 'Los Parques', 'Villa Universitaria', 'Los Lirios', 'Conjunto Residencial Los Urapanes', 'Conjunto Residencial La Alameda'],
    frequency: ['SAB'],
    schedule: '7:30 am a 2:00 pm',
  },
  {
    macroRoute: 'NOR ORIENTE',
    macroCode: '103115001',
    microCode: 'NR0403',
    neighborhoods: ['Terrazas de Santa Inés', 'Conjunto Residencial La Gran Reserva'],
    frequency: ['SAB'],
    schedule: '7:30 am a 2:00 pm',
  },
  {
    macroRoute: 'NOR ORIENTE',
    macroCode: '103115001',
    microCode: 'NR0404',
    neighborhoods: ['Santa Inés', 'Terrazas Club House II', 'Remansos de Santa Inés', 'Edificio Interprise', 'Edificio Marca', 'Edificio La Estancia', 'Edificio San Jorge', 'Conjunto residencial Villa de Aranjuez'],
    frequency: ['SAB'],
    schedule: '7:30 am a 2:00 pm',
  },
  {
    macroRoute: 'NOR ORIENTE',
    macroCode: '103115001',
    microCode: 'NR0405',
    neighborhoods: ['Quince de Mayo', 'Las Quintas'],
    frequency: ['SAB'],
    schedule: '7:30 am a 2:00 pm',
  },
  {
    macroRoute: 'NOR ORIENTE',
    macroCode: '103115001',
    microCode: 'NR0406',
    neighborhoods: ['Conjunto Sargón Plaza', 'Conjunto Acarigua'],
    frequency: ['VIE'],
    schedule: '3:00 pm a 6:00 pm',
  },
  {
    macroRoute: 'NOR ORIENTE',
    macroCode: '103115001',
    microCode: 'NR0407',
    neighborhoods: ['Altos de Los Muiscas', 'Los Muiscas', 'Colinas de Zue', 'Suamox'],
    frequency: ['MAR'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'NOR ORIENTE',
    macroCode: '103115001',
    microCode: 'NR0408',
    neighborhoods: ['Los Muiscas', 'Corelco', 'Edificio Torres del Este'],
    frequency: ['MAR'],
    schedule: '8:00 am a 2:00 pm',
  },
  {
    macroRoute: 'NOR ORIENTE',
    macroCode: '103115001',
    microCode: 'NR0409',
    neighborhoods: ['Ventus Multifamiliar'],
    frequency: ['MAR'],
    schedule: '3:00 am a 6:00 pm',
  },
  {
    macroRoute: 'NOR OCCIDENTE',
    macroCode: '103215001',
    microCode: 'NC0501',
    neighborhoods: ['Conjunto Residencial Fontanella', 'Reina Cecilia I', 'Reina Cecilia II', 'Conjunto Campestre Punto 53', 'Conjunto Residencial La Esperanza', 'Conjunto Cerrado Arboleda Real', 'Mirador San Carlos', 'Alameda de Unicentro', 'Reserva Campestre', 'Pirandelo'],
    frequency: ['SAB'],
    schedule: '8:30 am a 5:00 pm',
  },
  {
    macroRoute: 'NOR OCCIDENTE',
    macroCode: '103215001',
    microCode: 'NC0502',
    neighborhoods: ['Comercio de los siguientes sectores', 'Nieves', 'Viaducto', 'Avenida Norte', 'Carrera Novena'],
    frequency: ['MAR', 'JUE'],
    schedule: '2:30 pm a 5:30 pm',
  },
  {
    macroRoute: 'NOR OCCIDENTE',
    macroCode: '103215001',
    microCode: 'NC0503',
    neighborhoods: ['Villa Luz', 'Poblado', 'Conjunto Residencial Altos de Villa Luz'],
    frequency: ['JUE'],
    schedule: '12:00 pm a 2:00 pm',
  },
  {
    macroRoute: 'NOR OCCIDENTE',
    macroCode: '103215001',
    microCode: 'NC0504',
    neighborhoods: ['Villa del Norte II', 'Asís Boyacense', 'Conjunto Residencial Parques del Nogal III', 'Buena Vista'],
    frequency: ['JUE'],
    schedule: '8:00 am a 12:00 pm',
  },
  {
    macroRoute: 'NOR OCCIDENTE',
    macroCode: '103215001',
    microCode: 'NC0505',
    neighborhoods: ['Villa Toledo', 'Los Corales', 'Montecarlo', 'Los Cedros', 'José Antonio Galán', 'Villa María', 'Santa Jacoba del Puerto'],
    frequency: ['VIE'],
    schedule: '9:00 am a 11:30 pm',
  },
  {
    macroRoute: 'NOR OCCIDENTE',
    macroCode: '103215001',
    microCode: 'NC0506',
    neighborhoods: ['Santa Rita', 'Soaquira', 'Mirador de Tunja', 'La Granja del Norte', 'Prados del Norte', 'Altos de Xue'],
    frequency: ['VIE'],
    schedule: '11:30 am a 2:30 pm',
  },
  {
    macroRoute: 'NOR OCCIDENTE',
    macroCode: '103215001',
    microCode: 'NC0507',
    neighborhoods: ['Estancia El Roble', 'J.J Camacho', 'Los Héroes'],
    frequency: ['SAB'],
    schedule: '7:30 am a 2:00 pm',
  },
  {
    macroRoute: 'NOR OCCIDENTE',
    macroCode: '103215001',
    microCode: 'NC0508',
    neighborhoods: ['San Rafael', 'Colinas del Norte', 'Bosques del Norte', 'Altos de San Diego'],
    frequency: ['SAB'],
    schedule: '7:30 am a 2:00 pm',
  },
  {
    macroRoute: 'NOR OCCIDENTE',
    macroCode: '103215001',
    microCode: 'NC0509',
    neighborhoods: ['Pozo de Donato', 'Canapro', 'Altos de Canapro', 'Los Rosales', 'Conjunto Residencial Mirador del Bosque'],
    frequency: ['SAB'],
    schedule: '7:30 am a 2:00 pm',
  },
  {
    macroRoute: 'NOR OCCIDENTE',
    macroCode: '103215001',
    microCode: 'NC0510',
    neighborhoods: ['Altos de Suamox', 'Palos Verdes', 'La Primavera', 'El Capitolio', 'Alcalá Real', 'Balcones de Terranova', 'San José De La Arboleda', 'Coeducadores', 'Prados de Alcalá Norte', 'torre Vizcaya'],
    frequency: ['SAB'],
    schedule: '7:30 am a 2:00 pm',
  },
  {
    macroRoute: 'NOR OCCIDENTE',
    macroCode: '103215001',
    microCode: 'NC0511',
    neighborhoods: ['Avenida Norte', 'Portal de Hunzaua', 'Balcones del Norte', 'Portal del Norte', 'Manantial del Norte', 'Portal de Canapro'],
    frequency: ['SAB'],
    schedule: '7:30 am a 2:00 pm',
  },
  {
    macroRoute: 'NOR OCCIDENTE',
    macroCode: '103215001',
    microCode: 'NC0512',
    neighborhoods: ['La Granja', 'Los Cristales', 'Edificio Astorga', 'J.J Camacho', 'Multifamiliar Cerros del Norte'],
    frequency: ['SAB'],
    schedule: '7:30 am a 2:00 pm',
  },
];
